### ISSUE TITLE
Publish as a Single File not working?  

### ISSUE THREAD

**Issue by fishjd** [ErikEJ/SqlCeNetCore#1]
Is anyone able to publish this as a single file application in and any .Net 6 or newer.   

My goal is to publish this with a small number of files, preferably a single *.exe.  I have an SqlCe program working in .Net Framework.  I am trying this to see if a single file publish is possible.  

When I publish it and run it, then it throws:  "Unhandled exception. System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle."   The app runs fine in Visual Studio.   The "publish" step is the problem. 

Using Revision:  ccbe4107e02bc0d7b36d191420dd59cef3cb1412

Using: Visual Studio 17.6.0. Preview 2.   

**Any** assistance would be appreciated.

**Comment by ErikEJ** [comment]
Single file publishing with native binaries is not possible
